[2024-09-28T13:50:04.825+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-28T13:50:04.838+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_backflip_v01.task1 manual__2024-09-28T13:50:03.565764+00:00 [queued]>
[2024-09-28T13:50:04.842+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_backflip_v01.task1 manual__2024-09-28T13:50:03.565764+00:00 [queued]>
[2024-09-28T13:50:04.842+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-28T13:50:04.848+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): task1> on 2024-09-28 13:50:03.565764+00:00
[2024-09-28T13:50:04.853+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6493) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-28T13:50:04.853+0000] {standard_task_runner.py:72} INFO - Started process 6499 to run task
[2024-09-28T13:50:04.852+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backflip_v01', 'task1', 'manual__2024-09-28T13:50:03.565764+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backflip.py', '--cfg-path', '/tmp/tmp2yg4m9zt']
[2024-09-28T13:50:04.854+0000] {standard_task_runner.py:105} INFO - Job 114: Subtask task1
[2024-09-28T13:50:04.874+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_catchup_backflip_v01.task1 manual__2024-09-28T13:50:03.565764+00:00 [running]> on host f9a59cccd6d1
[2024-09-28T13:50:04.919+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_with_catchup_backflip_v01' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2024-09-28T13:50:03.565764+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-28T13:50:03.565764+00:00'
[2024-09-28T13:50:04.921+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-28T13:50:04.938+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-28T13:50:04.939+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo This is a simple bash command']
[2024-09-28T13:50:04.945+0000] {subprocess.py:86} INFO - Output:
[2024-09-28T13:50:04.947+0000] {subprocess.py:93} INFO - This is a simple bash command
[2024-09-28T13:50:04.947+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-28T13:50:04.962+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-28T13:50:04.962+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_backflip_v01, task_id=task1, run_id=manual__2024-09-28T13:50:03.565764+00:00, execution_date=20240928T135003, start_date=20240928T135004, end_date=20240928T135004
[2024-09-28T13:50:04.994+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-28T13:50:05.004+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-28T13:50:05.004+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
