[2024-09-29T02:58:43.399+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-29T02:58:43.407+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_cron_expression_v03.task1 manual__2024-09-29T02:58:42.149939+00:00 [queued]>
[2024-09-29T02:58:43.411+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_cron_expression_v03.task1 manual__2024-09-29T02:58:42.149939+00:00 [queued]>
[2024-09-29T02:58:43.412+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-29T02:58:43.420+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): task1> on 2024-09-29 02:58:42.149939+00:00
[2024-09-29T02:58:43.425+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=16503) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T02:58:43.426+0000] {standard_task_runner.py:72} INFO - Started process 16504 to run task
[2024-09-29T02:58:43.425+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_cron_expression_v03', 'task1', 'manual__2024-09-29T02:58:42.149939+00:00', '--job-id', '195', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_cron_expression.py', '--cfg-path', '/tmp/tmpovbzep1t']
[2024-09-29T02:58:43.427+0000] {standard_task_runner.py:105} INFO - Job 195: Subtask task1
[2024-09-29T02:58:43.452+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_cron_expression_v03.task1 manual__2024-09-29T02:58:42.149939+00:00 [running]> on host f9a59cccd6d1
[2024-09-29T02:58:43.504+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_with_cron_expression_v03' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T02:58:42.149939+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-29T02:58:42.149939+00:00'
[2024-09-29T02:58:43.505+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-29T02:58:43.517+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-29T02:58:43.517+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo dag with cron expression']
[2024-09-29T02:58:43.523+0000] {subprocess.py:86} INFO - Output:
[2024-09-29T02:58:43.528+0000] {subprocess.py:93} INFO - dag with cron expression
[2024-09-29T02:58:43.528+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-29T02:58:43.540+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-29T02:58:43.541+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_cron_expression_v03, task_id=task1, run_id=manual__2024-09-29T02:58:42.149939+00:00, execution_date=20240929T025842, start_date=20240929T025843, end_date=20240929T025843
[2024-09-29T02:58:43.569+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-29T02:58:43.578+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-29T02:58:43.579+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
