[2024-09-29T03:37:55.216+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-29T03:37:55.226+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.delete_from_table scheduled__2024-09-27T00:00:00+00:00 [queued]>
[2024-09-29T03:37:55.231+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.delete_from_table scheduled__2024-09-27T00:00:00+00:00 [queued]>
[2024-09-29T03:37:55.232+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-29T03:37:55.239+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): delete_from_table> on 2024-09-27 00:00:00+00:00
[2024-09-29T03:37:55.247+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=20361) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T03:37:55.245+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'delete_from_table', 'scheduled__2024-09-27T00:00:00+00:00', '--job-id', '557', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp93c1qtk4']
[2024-09-29T03:37:55.248+0000] {standard_task_runner.py:72} INFO - Started process 20364 to run task
[2024-09-29T03:37:55.249+0000] {standard_task_runner.py:105} INFO - Job 557: Subtask delete_from_table
[2024-09-29T03:37:55.283+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.delete_from_table scheduled__2024-09-27T00:00:00+00:00 [running]> on host f9a59cccd6d1
[2024-09-29T03:37:55.363+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='delete_from_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-27T00:00:00+00:00'
[2024-09-29T03:37:55.366+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-29T03:37:55.376+0000] {sql.py:266} INFO - Executing: 
            delete from dag_runs where dt = '2024-09-27' and dag_id='dag_with_postgres_operator_v04'
            
[2024-09-29T03:37:55.382+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:37:55.388+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:37:55.394+0000] {sql.py:509} INFO - Running statement: 
            delete from dag_runs where dt = '2024-09-27' and dag_id='dag_with_postgres_operator_v04'
            , parameters: None
[2024-09-29T03:37:55.395+0000] {sql.py:518} INFO - Rows affected: 1
[2024-09-29T03:37:55.402+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-29T03:37:55.403+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v04, task_id=delete_from_table, run_id=scheduled__2024-09-27T00:00:00+00:00, execution_date=20240927T000000, start_date=20240929T033755, end_date=20240929T033755
[2024-09-29T03:37:55.431+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-29T03:37:55.444+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-29T03:37:55.446+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
