[2024-09-29T03:16:42.594+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-29T03:16:42.604+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2024-09-26T00:00:00+00:00 [queued]>
[2024-09-29T03:16:42.610+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2024-09-26T00:00:00+00:00 [queued]>
[2024-09-29T03:16:42.611+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-29T03:16:42.625+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2024-09-26 00:00:00+00:00
[2024-09-29T03:16:42.630+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=18182) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T03:16:42.631+0000] {standard_task_runner.py:72} INFO - Started process 18187 to run task
[2024-09-29T03:16:42.630+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'insert_into_table', 'scheduled__2024-09-26T00:00:00+00:00', '--job-id', '328', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpjl814mg0']
[2024-09-29T03:16:42.632+0000] {standard_task_runner.py:105} INFO - Job 328: Subtask insert_into_table
[2024-09-29T03:16:42.657+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2024-09-26T00:00:00+00:00 [running]> on host f9a59cccd6d1
[2024-09-29T03:16:42.715+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-26T00:00:00+00:00'
[2024-09-29T03:16:42.716+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-29T03:16:42.726+0000] {sql.py:266} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2024-09-26', 'dag_with_postgres_operator_v03')
            
[2024-09-29T03:16:42.731+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:16:42.739+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:16:42.746+0000] {sql.py:509} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2024-09-26', 'dag_with_postgres_operator_v03')
            , parameters: None
[2024-09-29T03:16:42.747+0000] {sql.py:518} INFO - Rows affected: 1
[2024-09-29T03:16:42.754+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-29T03:16:42.754+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v03, task_id=insert_into_table, run_id=scheduled__2024-09-26T00:00:00+00:00, execution_date=20240926T000000, start_date=20240929T031642, end_date=20240929T031642
[2024-09-29T03:16:42.771+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-29T03:16:42.781+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-29T03:16:42.782+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
